// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHc6c7mooh-wKqN5ToPh2KVx9QSWRzPf0',
    appId: '1:789821321613:android:63dd4302ddbedc4967cdc4',
    messagingSenderId: '387350224750',
    projectId: 'foodrescue-da861',
    storageBucket: 'foodrescue-da861.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0sG6q5toP5Ev5A1Z_52BIJYIiCjFG-A',
    appId: '1:387350224750:ios:a1f40b9d6fe657de7b2b7f',
    messagingSenderId: '387350224750',
    projectId: 'foodrescue-da861',
    storageBucket: 'foodrescue-da861.appspot.com',
    iosBundleId: 'com.foods_rescue',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTy9aVbHvWXSQOvSFSqYE12Y4AKFtCPw',
    appId: '1:387350224750:web:76f420842c960f647b2b7f',
    messagingSenderId: '387350224750',
    projectId: 'foodrescue-da861',
    authDomain: 'foodrescue-da861.firebaseapp.com',
    storageBucket: 'foodrescue-da861.appspot.com',
    measurementId: 'G-0N500SSVZ5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe0sG6q5toP5Ev5A1Z_52BIJYIiCjFG-A',
    appId: '1:387350224750:ios:a1f40b9d6fe657de7b2b7f',
    messagingSenderId: '387350224750',
    projectId: 'foodrescue-da861',
    storageBucket: 'foodrescue-da861.appspot.com',
    iosBundleId: 'com.foods_rescue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaTy9aVbHvWXSQOvSFSqYE12Y4AKFtCPw',
    appId: '1:387350224750:web:e2dd09deca794eed7b2b7f',
    messagingSenderId: '387350224750',
    projectId: 'foodrescue-da861',
    authDomain: 'foodrescue-da861.firebaseapp.com',
    storageBucket: 'foodrescue-da861.appspot.com',
    measurementId: 'G-PLQ27C61YN',
  );
}
